version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: broker
    networks:
      - sport-app-network

  parametros-salud:
    build: ./parametros-salud
    container_name: parametros-salud
    volumes:
      - ./parametros-salud:/app
    networks:
      - sport-app-network

  monitor:
    build: ./monitor
    container_name: monitor
    volumes:
      - ./monitor:/app
    networks:
      - sport-app-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - parametros-salud
      - monitor
    networks:
      - sport-app-network

networks:
  sport-app-network:
