version: "3.9"

services:
  # redis:
  #   image: redis:alpine
  #   container_name: broker
  #   networks:
  #     - sport-app-network

  autorizador:
    build: ./autorizador
    container_name: autorizador
    volumes:
      - ./autorizador:/app
    networks:
      - sport-app-network

  usuario:
    build: ./usuario
    container_name: usuario
    volumes:
      - ./usuario:/app
    networks:
      - sport-app-network

  login:
    build: ./login
    container_name: login
    volumes:
      - ./login:/app
    networks:
      - sport-app-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - autorizador
      - usuario
      - login
    networks:
      - sport-app-network

networks:
  sport-app-network:
